USE MASTER
GO
--Create the server audit
CREATE SERVER AUDIT login_perm_audit
TO SECURITY_LOG
GO
--Enable the server audit
ALTER SERVER AUDIT login_perm_audit
WITH (STATE = ON) ;
GO
ALTER SERVER AUDIT SPECIFICATION login_audit_spec
FOR SERVER AUDIT login_perm_audit
ADD (SERVER_PERMISSION_CHANGE_GROUP),
ADD (SERVER_PRINCIPAL_CHANGE_GROUP),
ADD (SERVER_ROLE_MEMBER_CHANGE_GROUP),
ADD (FAILED_LOGIN_GROUP)
WITH ( STATE = ON )


